### ISSUE TITLE
Systematic Reviews (SR) dataset

### ISSUE THREAD

**Issue by ruisi-su** [Mihir3009/In-BoXBART#1]
Hi,

Is the SR dataset suite (including (1) Hormone Replacement Therapy (HRT), (2) Cooking, (3) Accelerometer, (4) Acromegaly, and (5) COVID) publicly available? I tried looking into the [original](https://keep.lib.asu.edu/_flysystem/fedora/c7/Parmar_asu_0010N_21179.pdf) paper, but could not find any links to the dataset. Our group is trying to gather a large set of biomedical datasets across different domains, and we think it will be very useful to also cover the datasets you have mentioned in the In-BoXBART paper. Thanks in advance!

**Comment by Mirzyaaliii** [comment]
Hello @ruisi-su,

We used Systematic Review datasets provided by Mayo Clinic and Arizona State University collaboration. These datasets are not publicly available. These datasets are created by one of the authors of our paper (M. Hassan Murad).

You can contact him at [murad.Mohammad@mayo.edu](murad.Mohammad@mayo.edu) to get permission for the data.

Hope this will help!!
