### ISSUE TITLE
About preprocessed dataset

### ISSUE THREAD

**Issue by Xiao9905** [Mihir3009/In-BoXBART#2]
Hi @Mihir3009 ,

Thanks for your great work! It is really fascinating and I am wondering if it is possible for you to provide a preprocessed corpus of all datasets in a seq2seq format? 

Thanks!

**Comment by Mirzyaaliii** [comment]
Hello @Xiao9905,

All original datasets that we used in our paper are licenced. Hence, we cannot release the dataset instances. You can go to the respective website and download the dataset from there. 

All preprocessing methods are presented in our paper (Section 5.1). You can see examples of preprocessed instances of each task in Appendix B. Moreover, if you want to use corresponding dataset instructions, you can check [here](https://github.com/Mihir3009/In-BoXBART/blob/main/templates/BoX_instructions.json).

Hope this will help!!
